{"name": "test_b", "status": "skipped", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <Test_App5.Test_ABC object at 0x0471AB10>\n\n    @pytest.mark.xfail(2 > 1, reason=\"标注为预期失败\") # 标记为预期失败函数test_b\n    def test_b(self):\n        print(\"------->test_b\")\n>       assert 0\nE       assert 0\n\nclsp\\Test_App5.py:14: AssertionError"}, "start": 1602663492034, "stop": 1602663492034, "uuid": "27b7a333-8b2e-45d9-a3f2-9d5d4f803cea", "historyId": "02ec5513fe8c67f3f444c5658bcbbcdc", "testCaseId": "c8c20521d02f46a9c22d349c9b0f5dc3", "fullName": "clsp.Test_App5.Test_ABC#test_b", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(True, reason='标注为预期失败')"}, {"name": "parentSuite", "value": "clsp"}, {"name": "suite", "value": "Test_App5"}, {"name": "subSuite", "value": "Test_ABC"}, {"name": "host", "value": "LAPTOP-LFNOOUSC"}, {"name": "thread", "value": "15616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "clsp.Test_App5"}]}